### ISSUE TITLE
Guzzle Library

### ISSUE THREAD

**Issue by mdestafadilah** [MythicalLTD/AAPanel-API#2]
any plan using guzzle or dev with it?

**Comment by NaysKutzu** [comment]
Hi yes I will continue the lib because I'm working on a dashboard for free and paid hosts to be able to create game servers in pterodactyl and websites in cloudpanel cPanel etc. Feel free to pull request

**Comment by mdestafadilah** [comment]
> Hi yes I will continue the lib because I'm working on a dashboard for free and paid hosts to be able to create game servers in pterodactyl and websites in cloudpanel cPanel etc. Feel free to pull request

Nice to hear, maybe next project i will create PR for using guzzle instead of using curl by default. i'm still testing for it.

**Comment by NaysKutzu** [comment]
ok sounds good!

**Comment by NaysKutzu** [comment]
can i close this?

**Comment by mdestafadilah** [comment]
yes, i've not more time, may if i've project aapanel, i will do this.
