### ISSUE TITLE
Cannot create FTP and Database with API

### ISSUE THREAD

**Issue by thanhansoft** [MythicalLTD/AAPanel-API#3]
I tried addSite function add FTP user, FTP password, dabtase user, database password but it doesn't work.
Result: [ftpStatus] => , [databaseStatus] => is NULL

`    $result = $aapanel->addSite($domain, $domain, $domain, $type_id = 0, $type = 'php', $phpversion = '73', $port = '80', $ftp = true, $ftpusername = $user, $ftppassword = $pass, $sql = true, $userdbase = $user, $passdbase = $pass, $setSsl = 1, $forceSsl = 1);
`

**Comment by NaysKutzu** [comment]
> I tried addSite function add FTP user, FTP password, dabtase user, database password but it doesn't work.
> Result: [ftpStatus] => , [databaseStatus] => is NULL
> 
> `    $result = $aapanel->addSite($domain, $domain, $domain, $type_id = 0, $type = 'php', $phpversion = '73', $port = '80', $ftp = true, $ftpusername = $user, $ftppassword = $pass, $sql = true, $userdbase = $user, $passdbase = $pass, $setSsl = 1, $forceSsl = 1);
> `

I will take a look at it are you sure you have everything setup right?
